name = "botgroupchat"
compatibility_date = "2025-3-20"
main = "./dist/index.html"  # 确保指向正确的入口文件

[site]
bucket = "./dist"  # 指向 React 构建后的静态文件目录
entry-point = "./dist"  # 可选，确保指向正确的目录

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.